### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by mozhn** [ConnectyCube/connectycube-cordova-samples#1]
I get an error after running the project. 
<img width="861" alt="Screen Shot 2020-05-25 at 18 05 05" src="https://user-images.githubusercontent.com/25257157/82824591-452a7880-9eb2-11ea-9cc9-a1fc0bc1cbde.png">

**Comment by DaveLomber** [comment]
@mozhn which sample are you trying to run? p2p calling or conference calling ?

**Comment by mozhn** [comment]
P2p calling

**Comment by DaveLomber** [comment]
This sample is for Cordova 9, let me know which ver are you using  

You also can try to build the sample from scratch using this guide 
https://developers.connectycube.com/cordova/code-samples-videochat-cordova

**Comment by shubham1397** [comment]
i am using cordova 9. but still getting same error

**Comment by mozhn** [comment]
> This sample is for Cordova 9, let me know which ver are you using
> 
> You also can try to build the sample from scratch using this guide
> https://developers.connectycube.com/cordova/code-samples-videochat-cordova

I gave up using it. I wrote my own system.

**Comment by ccvlad** [comment]
Closed due to inactivity. Please re-open if the issue is still persists.
