### ISSUE TITLE
need detailed explanation of session connections state in the documentation

### ISSUE THREAD

**Issue by azizcreativitykw** [ConnectyCube/connectycube-cordova-samples#10]
hi 
I am working on connect cube js SDK for the past couple of days
I am only able to log CONNECTING & CONNECTED status
I want to log other statuses so that I can hook my code into it
so it's my request to explain each session status in detail like when will it happen

**Comment by ccvlad** [comment]
- [isConnected](https://developers.connectycube.com/js/messaging?id=connection-status)
- status [disconnected](https://developers.connectycube.com/js/messaging?id=disconnect) via listener
- status [reconnected](https://developers.connectycube.com/js/messaging?id=reconnection) via listener

Also:
```javascript
// connecting
ConnectyCube.chat
  .connect(userCredentials)
  .then(() => {
    // connected
  })
  .catch((error) => {
     // failed
  });
```

**Comment by azizcreativitykw** [comment]
@ccvlad 
I think you didn't get my point
I mean to say, I want to know about each session states, when will it happen

ConnectyCube.videochat.SessionConnectionState.UNDEFINED
ConnectyCube.videochat.SessionConnectionState.CONNECTING
ConnectyCube.videochat.SessionConnectionState.CONNECTED
ConnectyCube.videochat.SessionConnectionState.FAILED
ConnectyCube.videochat.SessionConnectionState.DISCONNECTED
ConnectyCube.videochat.SessionConnectionState.CLOSED
ConnectyCube.videochat.SessionConnectionState.COMPLETED

**Comment by ccvlad** [comment]
You should have clarified that this is a video chat...

It is state of the ICE agent of the RTCPeerConnection. You are able to find descriptions of RTCPeerConnection.iceConnectionState [here](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceConnectionState).

**Comment by azizcreativitykw** [comment]
k 
but when i listen to `onSessionConnectionStateChangedListener` 
i am only getting two status CONNECTING & CONNECTED

**Comment by ccvlad** [comment]
The SDK has listeners for every case: onCallListener, onAcceptCallListener, onRejectCallListener, onStopCallListener, onUserNotAnswerListener, onRemoteStreamListener, onDevicesChangeListener... This is enough to apply all the necessary logic.

The `onSessionConnectionStateChangedListener ` just retranslates states from `RTCPeerConnection.iceConnectionState`. The ConnectyCube SDK uses some of this states inside.

Some description what I know:
- a 'checking' status the same with CONNECTING.
- the 'connected' and 'completed' almost always run at the same time (CONNECTED/COMPLETED).
- you will be able to get the DISCONNECTED or FAILED if the connection breaks on the opponent's side.
- a 'closed' (CLOSED) status does not fired in Safari browser.
- 'failed', 'disconnected' and 'closed' notify about disconnect
