### ISSUE TITLE
can we access the record feature in cordova?

### ISSUE THREAD

**Issue by nsxer007** [ConnectyCube/connectycube-cordova-samples#2]
I'd like to record the client side video in high quality so that I can upload it to our server after our 1 to 1 video chat. Think of this like a golf coaching app... We have a 1 on 1 session and then my app will upload the video to our server afterwards for archive, etc. 
I can't seem to find the api to initiate/store the video stream. Thanks for any help or direction!

**Comment by DaveLomber** [comment]
For this the MediaRecorder JS API can be used

1. Just start with the following links to understand how it works 

- https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder
- https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

2. So you can record a 'stream' object. 

To access local media stream - check this https://developers.connectycube.com/js/videocalling?id=access-local-media-stream

To access remote video stream - check this https://developers.connectycube.com/js/videocalling?id=accept-a-call.  `onRemoteStreamListener`

3. Once a recorded file is done - you can upload it to ConnectyCube storage for a later access https://developers.connectycube.com/js/messaging?id=attachments

**Comment by nsxer007** [comment]
You are the best! Thank you for responding!!



Thank you!
Jared

**Comment by DaveLomber** [comment]
@nsxer007 great to hear it !
