### ISSUE TITLE
iOS: undefined is not an object (evaluating 'p.getUserMedia') in cubeWebRTCSession line no 67

### ISSUE THREAD

**Issue by azizcreativitykw** [ConnectyCube/connectycube-cordova-samples#6]
Hi, My name is Aziz.

we have integrated ConnectiCube Js SDK in one of our Cordova Ionic 1 project
on android, it's working absolutely fine
but on iOS it's not working

when we build our app using Xcode & install the app for the very first time then it works

as soon as we restart the app and try to make a call, we get this error

we are in very big trouble because the project is almost completed & we are still getting the issue
plz plz fix it immediately 

plz find the below image for your reference

![Screen Shot 2020-11-03 at 8 23 17 PM](https://user-images.githubusercontent.com/66363246/98022499-c0576980-1e16-11eb-8f9a-f2b9b39332f8.png)

![Screen Shot 2020-11-03 at 8 42 19 PM](https://user-images.githubusercontent.com/66363246/98022445-b03f8a00-1e16-11eb-87da-f3e47602b778.png)

**Comment by azizcreativitykw** [comment]
![Screen Shot 2020-11-04 at 10 10 37 AM](https://user-images.githubusercontent.com/66363246/98080168-11527680-1e86-11eb-984d-25f283087135.png)


![Screen Shot 2020-11-04 at 10 10 50 AM](https://user-images.githubusercontent.com/66363246/98080185-19aab180-1e86-11eb-816f-eeb71f8e0e50.png)

**Comment by ccvlad** [comment]
Hi, Aziz!
The `cordova-plugin-iosrtc` did not connect by some reason.
Please, try `cordova plugin add cordova-plugin-iosrtc` one more time. Or `cordova plugin remove cordova-plugin-iosrtc 
 && cordova plugin add cordova-plugin-iosrtc`.

**Comment by azizcreativitykw** [comment]
hi @ccvlad 
thanks for the response 
but I don't think this is the solution
it's working only the first time when I installed the app from excode
when I restart the app it throws me this error

**Comment by DaveLomber** [comment]
@azizcreativitykw For iOS Cordova - a plugin should be installed and connected properly 

https://github.com/cordova-rtc/cordova-plugin-iosrtc

As for a help - please check this guide https://developers.connectycube.com/cordova/code-samples-videochat-cordova
especially - pay attention on 10 and 13 points, especially 13 point. 

`iosrtc.registerGlobals();` should be called before connecting ConnectyCube lib, cause it defines WebRTC primitives which  ConnectyCube lib uses. Please make sure it works this way.

**Comment by azizcreativitykw** [comment]
@DaveLomber 

may I know what do you mean by **connected properly**
I have installed properly 
but connected means what?

**Comment by DaveLomber** [comment]
If it works at least once then the lib is connected properly I assume

and the only one thing to double check is 13th point from the doc - the the lib is loaded into JS code

**Comment by azizcreativitykw** [comment]
hi @DaveLomber @ccvlad 

thanks for your help
finally, the issue is resolved now

the problem was we have to initialize connect cube after iosrtc plugin registers all the global
it means we have to use a timeout to defer the initialization on the iOS platform

you can close the issue

**Comment by DaveLomber** [comment]
@azizcreativitykw right, 
thank you for notifying us, glad to hear it works well 👍
