### ISSUE TITLE
wrong parameters in the documentation

### ISSUE THREAD

**Issue by azizcreativitykw** [ConnectyCube/connectycube-cordova-samples#9]
in the documentation

[https://developers.connectycube.com/js/videocalling?id=alwaysrelaycalls](https://developers.connectycube.com/js/videocalling?id=alwaysrelaycalls)

`const appConfig = {
  videocalling: {
    alwaysRelayCalls: true,
  },
};
`

in the library

[https://cdn.jsdelivr.net/npm/connectycube@3.7.2/lib/cubeConfig.js](https://cdn.jsdelivr.net/npm/connectycube@3.7.2/lib/cubeConfig.js)

![Screen Shot 2020-11-03 at 9 05 08 PM](https://user-images.githubusercontent.com/66363246/98023689-5b9d0e80-1e18-11eb-925c-2c599d065a77.png)

**Comment by ccvlad** [comment]
"... Setting it to true means the calling media will be routed through TURN server all the time, and not directly P2P between users even if the network path allows it."

`alwaysRelayCalls = false` uses by default. You can set `true` if you needed.

**Comment by azizcreativitykw** [comment]
no, I am taking about **videocalling** 
its not **videocalling** rather its a **videochat**

**Comment by ccvlad** [comment]
Hmm... I didn't pay attention. Sorry for that. I will fix it in the documentation. So the **videocalling** is wrong name, use **videochat** as property name.

**Comment by ccvlad** [comment]
@azizcreativitykw 

Fixed here: https://developers.connectycube.com/js/videocalling?id=alwaysrelaycalls

Thank you!
